spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## songs-service ----> http://localhost:8080/songs/ port forwarding auf http://localhost:9010/songs/
        - id: songs-service
          uri: lb://songs-service
          predicates:
            - Path=/songs/**

        ## songLists-service ----> http://localhost:8080/songLists/ port forwarding auf http://localhost:9010/songLists/
        - id: songs-service
          uri: lb://songs-service
          predicates:
            - Path=/songLists/**

        ## auth-service ----> http://localhost:8080/auth/ port forwarding auf http://localhost:9000/auth/
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        ## zelkulon-service ----> http://localhost:8080/zelkulon/ port forwarding auf http://localhost:9020
        - id: zelkulon-service
          uri: lb://zelkulon-service
          predicates:
            - Path=/esong/**


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/