spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## songs-service
        - id: songmicroservice
          uri: lb://songmicroservice
          predicates:
            - Path=/songs/**
          filters:
            - StripPrefix=1

        ## songLists-service
        - id: songLists
          uri: lb://songLists
          predicates:
            - Path=/songLists/**
          filters:
            - StripPrefix=1

        ## auth-service ----> http://localhost:8080/auth/songsMS/rest/auth funktioniert why?

        ## hier bitte stattdessen auf http://localhost:8080/songsMS/rest/auth
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/