spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## songs-service ----> http://localhost:8080/songs/ port forwarding auf http://localhost:9010/songs/
        - id: songmicroservice
          uri: lb://songmicroservice
          predicates:
            - Path=/songs/**

        ## songLists-service ----> http://localhost:8080/songLists/ port forwarding auf http://localhost:9010/songLists/
        - id: songLists
          uri: lb://songLists
          predicates:
            - Path=/songLists/**

        ## auth-service ----> http://localhost:8080/auth/ port forwarding auf http://localhost:9000/auth/
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/