DROP TABLE IF EXISTS usersonglist;
DROP TABLE IF EXISTS usertable;
DROP TABLE IF EXISTS song_list;


CREATE TABLE IF NOT EXISTS usertable(user_id VARCHAR(20) PRIMARY KEY, password VARCHAR(20) NOT NULL, firstName VARCHAR(50) NOT NULL, lastName VARCHAR(50) NOT NULL, token VARCHAR(100) NULL);

CREATE TABLE IF NOT EXISTS song_list(song_list_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY, is_private BOOLEAN NOT NULL DEFAULT TRUE,user_id VARCHAR(20) NOT NULL,name VARCHAR(50) NOT NULL,FOREIGN KEY (user_id) REFERENCES usertable(user_id));

INSERT INTO usertable (user_id, password, firstName, lastName) VALUES ('bschmitt', '123', 'Burkhart', 'Schmitt');

INSERT INTO usertable (user_id, password, firstName, lastName) VALUES ('maxime', 'pass1234', 'Maxime', 'Muster');

INSERT INTO usertable (user_id, password, firstName, lastName, token) VALUES ('jane', 'pass1234', 'Jane', 'Muster', 'validToken');

--CREATE TABLE IF NOT EXISTS usersonglist(owner VARCHAR(20) NOT NULL REFERENCES user_id,playlist INTEGER NOT NULL REFERENCES song_list_id,PRIMARY KEY (owner, playlist));


