CREATE TABLE IF NOT EXISTS songs (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,title VARCHAR(100) NOT NULL,artist VARCHAR(100),label VARCHAR(100),released INT);
CREATE TABLE IF NOT EXISTS song_list_songs(song_list_id INTEGER NOT NULL,song_id INTEGER NOT NULL,PRIMARY KEY(song_list_id, song_id),FOREIGN KEY(song_list_id) REFERENCES song_list(song_list_id),FOREIGN KEY(song_id) REFERENCES songs(id));
CREATE TABLE IF NOT EXISTS song_list(song_list_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,is_private BOOLEAN NOT NULL ,owner_id VARCHAR(20) NOT NULL,name VARCHAR(50) NOT NULL,FOREIGN KEY (owner_id) REFERENCES song_list(owner_id));
CREATE TABLE IF NOT EXISTS usertable(user_id VARCHAR(20) PRIMARY KEY, password VARCHAR(20) NOT NULL, firstName VARCHAR(50) NOT NULL, lastName VARCHAR(50) NOT NULL, token VARCHAR(100) NULL);
CREATE TABLE IF NOT EXISTS songs_list_song (song_list_id INTEGER,id INTEGER,PRIMARY KEY(song_list_id, id),FOREIGN KEY(song_list_id) REFERENCES song_list(song_list_id),FOREIGN KEY(id) REFERENCES songs(id));

INSERT INTO songs(id, title, artist, label, released) VALUES ('1', 'MacArthur Park', 'Richard Harris', 'Dunhill Records','1968');

INSERT INTO songs(id, title, artist, label, released) VALUES ('2', 'Afternoon Delight', 'Starland Vocal Band', 'Windsong','1976');

INSERT INTO songs(id, title, artist, label, released) VALUES ('3', 'Muskrat Love', 'Captain and Tennille', 'A&M','1976');

INSERT INTO songs(id, title, artist, label, released) VALUES ('4', 'Sussudio', 'Phil Collins', 'Virgin','1985');

INSERT INTO songs(id, title, artist, label, released) VALUES ('5', 'We Built This City', 'Starship', 'Grunt/RCA','1985');

INSERT INTO songs(id, title, artist, label, released) VALUES ('6', 'Achy Breaky Heart', 'Billy Ray Cyrus', 'PolyGram Mercury','1992');

INSERT INTO songs(id, title, artist, label, released) VALUES ('7', 'What’s Up?', '4 Non Blondes', 'Interscope','1993');

INSERT INTO songs(id, title, artist, label, released) VALUES ('8', 'Who Let the Dogs Out?', 'Baha Men', 'S-Curve','2000');

INSERT INTO songs(id, title, artist, label, released) VALUES ('9', 'My Humps', 'Black Eyed Peas', 'Universal Music','2005');

INSERT INTO songs(id, title, artist, label, released) VALUES ('10', 'Chinese Food', 'Alison Gold', 'PMW Live','2013');

INSERT INTO usertable (user_id, password, firstName, lastName) VALUES ('bschmitt', '123', 'Burkhart', 'Schmitt');

INSERT INTO usertable (user_id, password, firstName, lastName) VALUES ('maxime', 'pass1234', 'Maxime', 'Muster');

INSERT INTO usertable (user_id, password, firstName, lastName, token) VALUES ('jane', 'pass1234', 'Jane', 'Muster', 'validToken');

INSERT INTO usertable (user_id, password, firstName, lastName, token) VALUES ('fritz', 'pass1234', 'Fritz', 'Muster', 'qwertyuiiooxd1a245');


INSERT INTO song_list (owner_id, name, is_private) VALUES (TRUE, 'maxime', 'MaximesPrivate');
INSERT INTO song_list (owner_id, name, is_private) VALUES (FALSE, 'maxime', 'MaximesPublic');
INSERT INTO song_list (owner_id, name, is_private) VALUES (TRUE, 'jane', 'JanesPrivate');
INSERT INTO song_list (owner_id, name, is_private) VALUES (FALSE, 'jane', 'JanesPrivate');
