name: clean, build, test & package all projects

# Action will run on each push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # define os, versions, ...
    strategy:
      matrix:
        os: [ubuntu-latest]  # Changed from ubuntu-18.04
        java: [17]
    # run on os ...
    runs-on: ${{ matrix.os }}
    # all build steps
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 17
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
        architecture: x64
    - name: apigateway clean, build, test & package
      run: mvn -pl apigateway clean package
    - name: authmicroservice clean, build, test & package
      run: mvn -pl authmicroservice clean package
    - name: serviceregistry clean, build, test & package
      run: mvn -pl serviceregistry clean package
    - name: songmicroservice clean, build, test & package
      run: mvn -pl songmicroservice clean package
    - name: zelkulonmicroservice clean, build, test & package
      run: mvn -pl zelkulonmicroservice clean package
